### 등업 기준 조회
GET http://localhost:8080/rankup/search
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJFc2hIUnZsbHk1SitpeDEwLzJTWGxRPT0iLCJzdWIiOiJwdjVwQzNUOElkQTd3UncvbFZLcE13PT0iLCJyb2xlcyI6IkFETUlOIiwiaWF0IjoxNjg0OTg0OTMwLCJleHAiOjE2ODUwNzEzMzB9.Ofe3rv-8sPzEkkJf4S5BOuqpr7eqhcTHvU2RPKkkXKKwrN1oTRpWx7_TSZPgCWmr28UrY_ELPYk7LqZpVg4Eew


### 등업 기준 저장
POST http://localhost:8080/rankup/add
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJFc2hIUnZsbHk1SitpeDEwLzJTWGxRPT0iLCJzdWIiOiJwdjVwQzNUOElkQTd3UncvbFZLcE13PT0iLCJyb2xlcyI6IkFETUlOIiwiaWF0IjoxNjg0OTg0OTMwLCJleHAiOjE2ODUwNzEzMzB9.Ofe3rv-8sPzEkkJf4S5BOuqpr7eqhcTHvU2RPKkkXKKwrN1oTRpWx7_TSZPgCWmr28UrY_ELPYk7LqZpVg4Eew

{
  "rankName": "LEVEL3",
  "boardCount": 3,
  "commentCount": 3,
  "autoRankUpFlag": true
}


### 등업 기준 수정
PUT http://localhost:8080/rankup/modify/2
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJFc2hIUnZsbHk1SitpeDEwLzJTWGxRPT0iLCJzdWIiOiI4Y21vdWphU2EzNmpkeHltdWZHRC9YRHFCVW5PNlI3U1EyY0VUSEpsczdBPSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE2ODQ5MjU0MDgsImV4cCI6MTY4NTAxMTgwOH0.1Taliqx3wnWIWJ4BlO3PYLWx1dv2qWyihXCNsYTDhw02H9ka5-X2sAWKjDMGTRhNg6JuZGmVEvxXUVg3POqsbQ

{
  "boardCount": 10,
  "commentCount": 10,
  "autoRankUpFlag": true
}


### 등업 기준 삭제
DELETE http://localhost:8080/rankup/delete/3
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJFc2hIUnZsbHk1SitpeDEwLzJTWGxRPT0iLCJzdWIiOiI4Y21vdWphU2EzNmpkeHltdWZHRC9YRHFCVW5PNlI3U1EyY0VUSEpsczdBPSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE2ODQ5MjU0MDgsImV4cCI6MTY4NTAxMTgwOH0.1Taliqx3wnWIWJ4BlO3PYLWx1dv2qWyihXCNsYTDhw02H9ka5-X2sAWKjDMGTRhNg6JuZGmVEvxXUVg3POqsbQ

