### 게시글 목록 조회
GET http://localhost:8080/board/list
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTU5ODYwMCwiZXhwIjoxNjg1Njg1MDAwfQ.LsOukVhMdfCmE2g9SielHZnEsK7HjllacG6t8Lxn_mhS9W5YfkiaNx0ABZpLEFu_-e6KFJoUrAfwA_s2iJqG3A
#USER_TOKEN_HEADER:

{
  "page" : 0,
  "size": 20,
  "categoryId" : 0,
  "boardTitle": "",
  "nickName": ""
}


### 게시글 조회
GET http://localhost:8080/board/content
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJ1WXVtTmUxSHlCR2hHRVFubXEvYVN3PT0iLCJzdWIiOiJlbWhSYWNpbFRSNFRlTTJyQ3B2Wml3PT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTg2Mzg2NiwiZXhwIjoxNjg1OTUwMjY2fQ.COMxWfUtB3LEIwKTldMPgk_jPnXsJS-SwvkWiDBCSQ61MdjBG1p-Mcx9T_roDftqffsDNpaU45LndV51K-I7Cg

{
  "categoryId" : 3,
  "boardId": 1
}



### 게시글 저장
POST http://localhost:8080/board/content
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTg5NDIzOCwiZXhwIjoxNjg1OTgwNjM4fQ.eBuhIRcmhcFV6P5t-ACr8RVqoyZ2sSUcobM3RlNT5J6Bh8EBi3Ey3wztEKszCpuiEIRrO9lSONvEmNf8AuM6Dg

{
  "categoryId": 3,
  "boardTitle": "가나다라마바사~아자차카타파하~",
  "boardContent": "에헤 오에오에오오오~",
  "boardPublicFlag": true
}


### 게시글 수정
PUT http://localhost:8080/board/content/1
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTg2MzgxMywiZXhwIjoxNjg1OTUwMjEzfQ.UlqJ5PYr5vGqWVoPaiZO7iADxoRxzDm1P4Lqtc655wdW1aRLERMUgS3FAXlr7Oqf4qi3ZiFuaf7D1plqSn4XXA

{
  "categoryId": 3,
  "boardTitle": "가나다라마바사~아자차카타파하~",
  "boardContent": "에헤 오에오에오오오~",
  "boardPublicFlag": true
}


### 게시글 삭제
DELETE http://localhost:8080/board/content/1
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTU5ODY5NSwiZXhwIjoxNjg1Njg1MDk1fQ.jcWXQC67k51YIFUaavPbgX9-tOKpL4I61Jhb2mmdQ2lqbpwEdAjleeLXcXUCDM-YAuOoQUA9gcuOptHe-YlBlw
