### 관리자 회원가입
POST http://localhost:8080/signup/admin
Content-Type: application/json

{
  "loginId": "administrator",
  "userNickName": "관리자",
  "userPassword": "abcdefgh1!"
}


### 회원 회원가입
POST http://localhost:8080/signup/user
Content-Type: application/json

{
  "loginId": "ohdonggeon2",
  "userNickName": "먼지제거제2",
  "userPassword": "abcdefgh1!"
}


### 로그인
POST http://localhost:8080/signin
Content-Type: application/json

{
  "loginId": "ohdonggeon2",
  "userPassword": "abcdefgh1!"
}