### 회원가입
POST http://localhost:8080/user/signup
Content-Type: application/json

{
  "loginId": "중복확인",
  "userNickName": "닉네임",
  "userPassword": "159",
  "userRank": "0"
}


### 로그인
POST http://localhost:8080/user/signin
Content-Type: application/json

{
  "loginId": "중복확인",
  "userPassword": "159"
}


