### 게시글 목록 조회
GET http://localhost:8080/board/list
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTU5ODYwMCwiZXhwIjoxNjg1Njg1MDAwfQ.LsOukVhMdfCmE2g9SielHZnEsK7HjllacG6t8Lxn_mhS9W5YfkiaNx0ABZpLEFu_-e6KFJoUrAfwA_s2iJqG3A
#USER_TOKEN_HEADER:

{
  "page" : 0,
  "size": 20,
  "categoryId" : 0,
  "boardTitle": "",
  "nickName": ""
}


### 게시글 조회
GET http://localhost:8080/board/content
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTUyNjYxNCwiZXhwIjoxNjg1NjEzMDE0fQ.xUEy6_Ha42Rp0MOWT1nZKKKkBnBL65y62T9i6VSQKTOiBouqSyBle1oagCaeQy1yndoy7_6u_rdjwDbrGYsiaQ

{
  "categoryId" : 3,
  "boardId": 1
}



### 게시글 저장
POST http://localhost:8080/board/content
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTU5ODY5NSwiZXhwIjoxNjg1Njg1MDk1fQ.jcWXQC67k51YIFUaavPbgX9-tOKpL4I61Jhb2mmdQ2lqbpwEdAjleeLXcXUCDM-YAuOoQUA9gcuOptHe-YlBlw

{
  "categoryId": 3,
  "boardTitle": "가나다라마바사~아자차카타파하~",
  "boardContent": "에헤 오에오에오오오~",
  "boardPublicFlag": true
}


### 게시글 수정
PUT http://localhost:8080/board/content/1
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTU5ODY5NSwiZXhwIjoxNjg1Njg1MDk1fQ.jcWXQC67k51YIFUaavPbgX9-tOKpL4I61Jhb2mmdQ2lqbpwEdAjleeLXcXUCDM-YAuOoQUA9gcuOptHe-YlBlw

{
  "categoryId": 3,
  "boardTitle": "가나다라마바사~아자차카타파하~",
  "boardContent": "에헤 오에오에오오오~",
  "boardPublicFlag": false
}


### 게시글 삭제
DELETE http://localhost:8080/board/content/1
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJCc1hpbUpGQVRBbWwvYzhVdkF1KzB3PT0iLCJzdWIiOiI2RzZzeThTZVZBS0xseithNEN0RlJnPT0iLCJyb2xlcyI6IkxFVkVMMSIsImlhdCI6MTY4NTU5ODY5NSwiZXhwIjoxNjg1Njg1MDk1fQ.jcWXQC67k51YIFUaavPbgX9-tOKpL4I61Jhb2mmdQ2lqbpwEdAjleeLXcXUCDM-YAuOoQUA9gcuOptHe-YlBlw
