### 게시판 분류 조회
GET http://localhost:8080/category/search
Content-Type: application/json


### 게시판 분류 저장
POST http://localhost:8080/category/add
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJFc2hIUnZsbHk1SitpeDEwLzJTWGxRPT0iLCJzdWIiOiJwdjVwQzNUOElkQTd3UncvbFZLcE13PT0iLCJyb2xlcyI6IkFETUlOIiwiaWF0IjoxNjg1MTk5MDM1LCJleHAiOjE2ODUyODU0MzV9.Wb4FxIj3UDxUpq0BxBCjudvtKC7mJPuX0puvr8rdLAaBl2gjrquWGRP0lQn4S_GmU12Q-ydvNlXXLW7jrOe2kg

{
  "categoryTitle": "렙 1",
  "categoryRank": "LEVEL4",
  "categoryUesFlag": true
}


### 게시판 분류 수정
PUT http://localhost:8080/category/modify/1
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJFc2hIUnZsbHk1SitpeDEwLzJTWGxRPT0iLCJzdWIiOiJwdjVwQzNUOElkQTd3UncvbFZLcE13PT0iLCJyb2xlcyI6IkFETUlOIiwiaWF0IjoxNjg1MTk5MDM1LCJleHAiOjE2ODUyODU0MzV9.Wb4FxIj3UDxUpq0BxBCjudvtKC7mJPuX0puvr8rdLAaBl2gjrquWGRP0lQn4S_GmU12Q-ydvNlXXLW7jrOe2kg

{
  "categoryTitle": "LEVEL4 변경",
  "categoryRank": "LEVEL4",
  "categoryUesFlag": true
}


### 게시판 분류 삭제
DELETE http://localhost:8080/category/delete/1
Content-Type: application/json
USER_TOKEN_HEADER: eyJhbGciOiJIUzUxMiJ9.eyJqdGkiOiJFc2hIUnZsbHk1SitpeDEwLzJTWGxRPT0iLCJzdWIiOiJwdjVwQzNUOElkQTd3UncvbFZLcE13PT0iLCJyb2xlcyI6IkFETUlOIiwiaWF0IjoxNjg1MTk5ODMwLCJleHAiOjE2ODUyODYyMzB9.ph3WgddRzo9NgxW0fXNuplaNVOOPjn9gCphkXujMBEbguckh93pQ3fXM11GTiPkIAmNhMhUfb7lmIp0IhJU7KQ
